### ISSUE TITLE
Eloquent scopes removed from subqueries

### ISSUE THREAD

**Issue by oaklees** [reinink/laracon2018#5]
Hi Jonathan

Firstly, fantastic work here - it's really taken my queries to the next level, so thank you.

After using these methods 'in anger', one thing that did have me scratching my head for a good 20 minutes though, is that when you're passing Eloquent Building instances to the `addSubSelect` macro, the `getQuery` method on the builder returns the underlying query _without_ any applicable model scopes applied. This resulted in me getting some unexpected results as I had a number of global scopes being enforced..

After taking a look at the Eloquent Builder class, a `toBase` method exists which applies the scopes to the underlying query, so this can be used for in place of `getQuery` when an Eloquent Query Builder is passed to our macro instead. This then ensures any scopes are applied before being parsed to a sub-select 👌

```php
Builder::macro('addSubSelect', function ($query, $column) {
    if (is_null($this->getQuery()->columns)) {
        $this->select($this->getQuery()->from.'.*');
    }

    if ($query instanceof self) {
        return $this->selectSub($query->limit(1)->toBase(), $column);
    }

    return $this->selectSub($query->limit(1)->getQuery(), $column);
});
```
Happy to PR if you think it would be of benefit, but wanted to share nonetheless.

**Comment by reinink** [comment]
Really interesting, thanks for sharing this @jivemonkey2000! I actually just released [a package](https://github.com/reinink/advanced-eloquent) that includes this macro, except I removed the "getQuery()" call entirely. I think this was required at one time, but isn't anymore. I just tested it, and subquery scopes are applied perfectly. 👌
