### ISSUE TITLE
Fetch relations recursively avoiding n + 1 problem

### ISSUE THREAD

**Issue by fdalcin** [reinink/laracon2018#8]
Hello Jonathan,

I have a question that I would like you to share your thoughts about.
The question is about self relations and eager loading.

I have a table migration with a relation to itself as follows:

```php
Schema::create('employees', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->unsignedBigInteger('employee_id')->nullable();
    $table->string('name');
    ...
});
```
And in my Employee model I have a relation that returns subordinates for a given employee

```php
public function subordinates(): HasMany
{
    return $this->hasMany(Employee::class, 'employee_id');
}
```

Imagine the following data:

| ID | employee_id | name |
| :---: |     :---:      |          ---: |
| 1   | null     | John Doe    |
| 2     | 1       | Jane Doe      |
| 3     | 2       | Felipe Dalcin      |

The issue is that I need to retrieve subordinates recursively. When trying to return all John's subordinates it should return 

```json
[
  {"id": 2, "name": "Jane Doe"}, 
  {"id": 3, "Felipe Dalcin"}
]
```

Because all Jane's subordinates are also John's. 
The way it is designed right now will cause a n + 1 problem.

Is there a nicer way to avoid this and return it in a simpler way? Would you recommend a better solution?

Thanks in advance

**Comment by chelout** [comment]
If you use mysql 8, or postgres, you can do it with recursive cte.

**Comment by reinink** [comment]
@chelout That's awesome! Are you able to share a code example of that?

**Comment by chelout** [comment]
@reinink yeah, that's gonna be like this on mysql 8:
```sql
with recursive subordinates AS (
    select id, employee_id, name from employees where id = 1
    union all
    select employees.id, employees.employee_id, employees.name from employees
		inner join subordinates on subordinates.id = employees.employee_id
)
select * from subordinates;
```

**Comment by fdalcin** [comment]
@chelout yeah, that would be the best solution. 
Unfortunately MariaDB only supports that on 10.2 and I am not able to migrate at the moment.

Is there another way with a lower version?

Just one question about that solution, do I need to run the WITH RECURSIVE everytime? Or will it create some sort of table?

**Comment by chelout** [comment]
@fdalcin have a look https://stackoverflow.com/questions/20215744/how-to-create-a-mysql-hierarchical-recursive-query

**Comment by fdalcin** [comment]
@chelout It seems to me that this approach will work as expected:

```mysql
select id, employee_id, name
from (select * from employees order by employee_id, id) employee_list,
     (select @pv := 1) filter
where find_in_set(employee_id, @pv)
and length(@pv := concat(@pv, ',', id))
```

Thanks for your help
